version: '3.8'

services:
  app:
    build: .
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=my-secret-password
      - DB_DATABASE=mysql_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    ports:
      - "5000:5000"

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "mysql -h 'localhost' -u 'root' -p'my-secret-password' -e 'SELECT 1'"]
      timeout: 20s
      retries: 10
      interval: 10s
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-password
      MYSQL_DATABASE: mysql_db
    networks:
      - app-network
    ports:
      - "3306:3306"
volumes:
  db_data:

networks:
  app-network:
      
      
        
