apiVersion: v1
kind: Service
metadata:
  labels:
    app: todo-app
  name: todo-app
  namespace: app
spec:
  ports:
  - nodePort: 30000
    port: 80
    protocol: TCP
  selector:
    app: todo-app
  type: LoadBalancer