name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - master

jobs:
  build-docker:
    if: contains( github.event.head_commit.message, 'Update Helm values') != true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push the Docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}
          TAG_SHA=${{ steps.vars.outputs.sha_short }}

          docker build . --file Dockerfile \
            --tag $IMAGE_NAME:latest \
            --tag $IMAGE_NAME:$TAG_SHA

          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$TAG_SHA

  update-helm-values:
    runs-on: ubuntu-latest
    needs: build-docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update Helm values with GitHub SHA
        run: |
          GITHUB_SHA_SHORT=$(echo "${{ github.sha }}" | cut -c1-7)
          sudo snap install yq
          yq -i '.image.tag = "${GITHUB_SHA_SHORT}"' k8s/helm/values.yaml

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add k8s/helm/values.yaml
          git commit -m "Update Helm values with GitHub SHA $GITHUB_SHA_SHORT" || exit 0

      - name: Push changes
        run: |
          git push origin HEAD || exit 0
